name: The Bauzes
favicon: null
layout_spectrum: 0.8117400519549847
typography_spectrum: 0.1464235174935311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8200305260252208
  lightness: 0.3134819364640862
  saturation: 0.38586938311345875
  rhythmicContrast: 0.9849972503725439
purpose: []
